from app.models import OrchestrationInput, SignalNode


SAMPLE_ORCHESTRATIONS: list[OrchestrationInput] = [
    OrchestrationInput(
        orchestration_id="orch-northstar-ops",
        scenario_name="Northstar executive pressure map",
        environment="production",
        nodes=[
            SignalNode(
                signal_id="rev-coverage",
                lane="revenue",
                title="Pipeline coverage compression",
                owner="Revenue Operations",
                metric="coverage",
                current_value=2.1,
                target_value=3.0,
                confidence=0.86,
                severity="critical",
                due_in_days=8,
                dependencies=["growth-attribution", "ops-routing"],
                note="Coverage dip is being amplified by poor attribution confidence and delayed routing.",
            ),
            SignalNode(
                signal_id="growth-attribution",
                lane="growth",
                title="Attribution confidence drift",
                owner="Growth Analytics",
                metric="confidence",
                current_value=0.58,
                target_value=0.8,
                confidence=0.79,
                severity="high",
                due_in_days=6,
                dependencies=["ai-fallback"],
                note="Source weighting is masking the partner-to-revenue path.",
            ),
            SignalNode(
                signal_id="ops-routing",
                lane="ops",
                title="Routing backlog spillover",
                owner="Operations",
                metric="queue-hours",
                current_value=36.0,
                target_value=18.0,
                confidence=0.83,
                severity="high",
                due_in_days=5,
                dependencies=["security-reviews"],
                note="Escalations are waiting on ownership confirmation and identity review closure.",
            ),
            SignalNode(
                signal_id="ai-fallback",
                lane="ai",
                title="Prompt fallback inflation",
                owner="AI Platform",
                metric="fallback-rate",
                current_value=12.0,
                target_value=5.0,
                confidence=0.77,
                severity="moderate",
                due_in_days=4,
                dependencies=[],
                note="Safe fallback behavior is hiding a growing latency and cost pattern.",
            ),
            SignalNode(
                signal_id="security-reviews",
                lane="security",
                title="Access review backlog",
                owner="Security Operations",
                metric="open-reviews",
                current_value=41.0,
                target_value=20.0,
                confidence=0.91,
                severity="high",
                due_in_days=10,
                dependencies=[],
                note="Remediation timing is starting to block customer-facing changes.",
            ),
        ],
    ),
    OrchestrationInput(
        orchestration_id="orch-atlas-renewal",
        scenario_name="Atlas renewal recovery chain",
        environment="executive-review",
        nodes=[
            SignalNode(
                signal_id="cust-renewal",
                lane="customer",
                title="Renewal confidence slide",
                owner="Customer Success",
                metric="renewal-confidence",
                current_value=63.0,
                target_value=80.0,
                confidence=0.84,
                severity="critical",
                due_in_days=12,
                dependencies=["ops-approvals", "rev-forecast"],
                note="Trust and adoption pressure are converging close to the renewal window.",
            ),
            SignalNode(
                signal_id="ops-approvals",
                lane="ops",
                title="Approval path congestion",
                owner="Operations",
                metric="handoff-hours",
                current_value=28.0,
                target_value=16.0,
                confidence=0.81,
                severity="moderate",
                due_in_days=7,
                dependencies=[],
                note="Escalation ownership is too fragmented for a fast save motion.",
            ),
            SignalNode(
                signal_id="rev-forecast",
                lane="revenue",
                title="Commit risk concentration",
                owner="Sales Leadership",
                metric="commit-risk",
                current_value=37.0,
                target_value=18.0,
                confidence=0.82,
                severity="high",
                due_in_days=9,
                dependencies=[],
                note="Forecast confidence in the same segment is dropping alongside renewal certainty.",
            ),
        ],
    ),
]

